### ISSUE TITLE
(node:50093) UnhandledPromiseRejectionWarning: Error: spawn npm install ENOENT

### ISSUE THREAD

**Issue by cuijianjun** [woai3c/mini-cli#4]
v14.6.0 在mvc时候出现这个问题 install执行失败，您遇到过这个问题吗

**Comment by woai3c** [comment]
> v14.6.0 在mvc时候出现这个问题 install执行失败，您遇到过这个问题吗

不好意思，我没用过这个问题。我的系统用过 12 和 14 的都没出现这个问题，建议你百度或 google 一下。我 google 到这篇文章 https://blog.csdn.net/sikichan/article/details/52087597，不知道能不能帮到你？

**Comment by 17biubiu** [comment]
@cuijianjun 不知道你解决了没？我也碰到了这个问题
