### ISSUE TITLE
runTransformation不太懂，请楼主指教哈

### ISSUE THREAD

**Issue by yangfan-coder** [woai3c/mini-cli#5]
背景：在看vue-cli的源码，但是代码量较大随即找到当前的项目文件、进行本地学习，看到了在`lib/Generator.js`文件中的`runTransformation` 方法，有些不懂里面的逻辑，尤其是`lib/utils/codemods/injectImports.js`文件中写的，只找到了当前的github但是详细的文档没有找到，请问楼主之前写的时候 有相关资料和或者见解吗
我看是V2的分支哈

**Comment by woai3c** [comment]
就是代码文件中的这些句子 `import a from 'a'` 引进来。我觉得你可以打一下断点，vscode 可以对 nodejs 程序打断点的。你就在这个方法里打断点，看一下方法的输入和输出，你就明白是干什么用的了。

**Comment by yangfan-coder** [comment]
> 就是代码文件中的这些句子 `import a from 'a'` 引进来。我觉得你可以打一下断点，vscode 可以对 nodejs 程序打断点的。你就在这个方法里打断点，看一下方法的输入和输出，你就明白是干什么用的了。

好的吧、感谢
