### ISSUE TITLE
v4版本下载依赖报错

### ISSUE THREAD

**Issue by missXing** [woai3c/mini-cli#7]
<img width="914" alt="image" src="https://user-images.githubusercontent.com/19276241/195410675-a15b3a49-2caf-4041-8958-04b030eef734.png">
使用v4版本 总是报这个错。。。换了npm镜像也不行 求指导~

**Comment by woai3c** [comment]
你改代码了吧，没有 `mx-cli-plugin-babel` 这个依赖。

**Comment by missXing** [comment]
嗯嗯 我是按照教程自己敲了一遍
执行了：
lerna create mx-cli-plugin-babel
lerna add mx-cli-plugin-babel --scope=mx-monorepo-cli

mx-monorepo-cli 是入口 相当于mvc-cli-base
也安装了：
![image](https://user-images.githubusercontent.com/19276241/195538910-79481377-b731-4c3c-8b9e-5ed8925b53dc.png)

![image](https://user-images.githubusercontent.com/19276241/195539105-ef048161-e12a-46df-8a9f-fb9258fd2c72.png)

![image](https://user-images.githubusercontent.com/19276241/195539222-23ccc14e-6c3c-41a6-a1b8-bd5b9a143126.png)

**Comment by missXing** [comment]
我刚试了一下你的代码是没有问题 我是奇怪我哪里做错了 明明有依赖却说找不到 一般会因为什么出现这种情况？ 我自己再查查 希望可以得到你的建议 （排查方向）

**Comment by woai3c** [comment]
> 我刚试了一下你的代码是没有问题 我是奇怪我哪里做错了 明明有依赖却说找不到 一般会因为什么出现这种情况？ 我自己再查查 希望可以得到你的建议 （排查方向）

先从不会报错的版本逐步迭代，找到有错误的那个版本再看。从你的报错信息看，是没有把这个包注册到 npm，所以找不到。

**Comment by missXing** [comment]
本地开发不是不需要把包注册到npm嘛？ 直接引用的是本地的包 比如截图的这个报错他应该直接使用的：packages/mx-cli-plugin-babel 这个文件吧

**Comment by woai3c** [comment]
> 本地开发不是不需要把包注册到npm嘛？ 直接引用的是本地的包 比如截图的这个报错他应该直接使用的：packages/mx-cli-plugin-babel 这个文件吧

是的 但是没在你本地找到这个包。你得找找问题出在哪。

**Comment by missXing** [comment]
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/19276241/195578690-54d1bfdb-8e70-4c03-b76a-fc36958fbf05.png">
我貌似知道怎么回事了 我刚看了一下用你的脚手架创建出来的项目依赖里有mvc-cli-plugin-babel  这个是不符合预期的吧 在用脚手架创建好的项目里安转依赖就是从npm获取的了 所以我这边没有发包就一直报错

**Comment by missXing** [comment]
`answers.features.forEach(feature => {
        if (feature !== 'service') {
            pkg.devDependencies[`mx-cli-plugin-${feature}`] = '~1.0.0'
        } else {
            pkg.devDependencies['mx-cli-service'] = '~1.0.0'
        }
    })
`
我发现把create.js中的这段注释掉就可以了 脚手架创建的项目使用也没有问题 想问一下为啥要加这一段呀~~？

**Comment by missXing** [comment]
看到了 你是想让用户下载mvc-cli-service 这个插件进行 build  那就是mvc-cli-service一定要发布成包 上面说的那一句改成：
`
    answers.features.forEach(feature => {
        if (feature === 'service') {
            pkg.devDependencies['mvc-cli-service'] = '~0.0.1'
        }
    })
`
就可以了
